# Restrict to the target platforms
PLATFORMS_ONLY += nrf
TARGET ?= nrf
BOARD ?=conexio-stratus

CONTIKI_PROJECT = hello-world
all: $(CONTIKI_PROJECT)

CONTIKI = ../../..
include $(CONTIKI)/Makefile.include

