BOARD_SOURCEFILES += board-leds.c
BOARD_SOURCEFILES += board-buttons.c
BOARD_SOURCEFILES += board-sensors.c

CONTIKI_TARGET_DIRS += conexio-stratus

### Include the common Conexio Stratus makefile
include $(PLATFORM_ROOT_DIR)/conexio-stratus/Makefile.conexio-stratus

CFLAGS += -DBOARD_CONF_PATH=\"conexio-stratus-conf.h\"

### Will allow the inclusion of the correct CPU makefile
CPU_FAMILY = nrf9160