### Will allow the inclusion of the correct CPU makefile
CPU_FAMILY = nrf9160

### Include the common dk makefile
include $(PLATFORM_ROOT_DIR)/nrf9160/dk/Makefile.dk

BOARD_SOURCEFILES += board-leds.c
BOARD_SOURCEFILES += board-buttons.c
BOARD_SOURCEFILES += board-sensors.c

CFLAGS += -DBOARD_CONF_PATH=\"nrf9160-dk-conf.h\"

CONTIKI_TARGET_DIRS += nrf9160/dk
