BOARD_SOURCEFILES += board-leds.c
BOARD_SOURCEFILES += board-buttons.c
BOARD_SOURCEFILES += board-sensors.c

CONTIKI_TARGET_DIRS += nrf9160

### Include the common nrf9160 makefile
include $(PLATFORM_ROOT_DIR)/nrf9160/Makefile.nrf9160

CFLAGS += -DBOARD_CONF_PATH=\"nrf9160-conf.h\"

### Will allow the inclusion of the correct CPU makefile
CPU_FAMILY = nrf9160